{
 "title": "Wlanthermo Nano",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "channels",
    "label": "Channels",
    "query": "Channel 1,Channel 2,Channel 3,Channel 4,Channel 5,Channel 6,Channel 7,Channel 8"
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "HW version",
     "measurement": "System settings",
     "query": "SELECT last(\"hwversion\") FROM \"System settings\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "hwversion" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "SW version",
     "measurement": "System settings",
     "query": "SELECT last(\"version\") FROM \"System settings\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Hostname",
     "measurement": "System settings",
     "query": "SELECT last(\"host\") FROM \"System settings\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "host" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "measurement": "System",
     "query": "SELECT last(\"soc\") FROM \"System\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "soc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "measurement": "System",
     "query": "SELECT last(\"rssi\") FROM \"System\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "History",
   "type": "ryantxu-annolist-panel",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WlanThermo temperatures",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "celsius", "label": "°C" }
   ],
   "targets": [
    {
     "alias": "$tag_alias  ($tag_channel)",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "alias" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "channel 1",
     "query": "SELECT median(\"temp\") FROM \"Temperature\" WHERE $timeFilter GROUP BY time(30s), \"channel\", \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "repeat": "channels",
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[channels]]",
     "measurement": "/^$channels$/",
     "query": "SELECT last(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "[[channels]]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 15 },
   "repeat": "channels",
   "yaxes": [
    { "format": "celsius", "label": "°C" }
   ],
   "targets": [
    {
     "alias": "$tag_alias",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$channels$/",
     "query": "SELECT mean(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (max)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"max\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"min\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[channels]]",
     "measurement": "/^$channels$/",
     "query": "SELECT last(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "[[channels]]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 20 },
   "yaxes": [
    { "format": "celsius", "label": "°C" }
   ],
   "targets": [
    {
     "alias": "$tag_alias",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$channels$/",
     "query": "SELECT mean(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (max)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"max\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"min\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 25 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[channels]]",
     "measurement": "/^$channels$/",
     "query": "SELECT last(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "[[channels]]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 25 },
   "yaxes": [
    { "format": "celsius", "label": "°C" }
   ],
   "targets": [
    {
     "alias": "$tag_alias",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$channels$/",
     "query": "SELECT mean(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (max)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"max\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"min\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 30 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[channels]]",
     "measurement": "/^$channels$/",
     "query": "SELECT last(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "[[channels]]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 30 },
   "yaxes": [
    { "format": "celsius", "label": "°C" }
   ],
   "targets": [
    {
     "alias": "$tag_alias",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$channels$/",
     "query": "SELECT mean(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (max)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"max\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"min\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 35 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[channels]]",
     "measurement": "/^$channels$/",
     "query": "SELECT last(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "[[channels]]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 35 },
   "yaxes": [
    { "format": "celsius", "label": "°C" }
   ],
   "targets": [
    {
     "alias": "$tag_alias",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$channels$/",
     "query": "SELECT mean(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (max)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"max\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"min\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 40 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[channels]]",
     "measurement": "/^$channels$/",
     "query": "SELECT last(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "[[channels]]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 40 },
   "yaxes": [
    { "format": "celsius", "label": "°C" }
   ],
   "targets": [
    {
     "alias": "$tag_alias",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$channels$/",
     "query": "SELECT mean(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (max)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"max\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"min\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 45 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[channels]]",
     "measurement": "/^$channels$/",
     "query": "SELECT last(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "[[channels]]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 45 },
   "yaxes": [
    { "format": "celsius", "label": "°C" }
   ],
   "targets": [
    {
     "alias": "$tag_alias",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$channels$/",
     "query": "SELECT mean(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (max)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"max\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"min\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 50 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "[[channels]]",
     "measurement": "/^$channels$/",
     "query": "SELECT last(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "[[channels]]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 50 },
   "yaxes": [
    { "format": "celsius", "label": "°C" }
   ],
   "targets": [
    {
     "alias": "$tag_alias",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$channels$/",
     "query": "SELECT mean(\"temp\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (max)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"max\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_alias (min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT median(\"min\") FROM \"Temperature\" WHERE $timeFilter AND \"channel\" = '$channels'  GROUP BY time(30s), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}